name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:
  test:
    name: Test
    runs-on: macOS-13
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: set -o pipefail && xcodebuild test -scheme FindFaster -destination "platform=macOS" | xcpretty
